#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <libgen.h>
#include <sys/types.h>
#include <sys/stat.h>

void fputs_wrap_nl(FILE* dest, const char* string, int wrap_point)
{ // Didn't find use for this fun
  int len = strlen(string);
  size_t i = 0;
  size_t spacept = 0;
  char buf[wrap_point + 1];

  buf[wrap_point + 1] = 0;
  while(i < len) {
    for(; i < wrap_point; i++) {
      if(string[i] == ' ') {
        spacept = i;
      }
    }
    strncpy(buf, string, wrap_point % spacept);
    fputs(buf, dest);
    fputc('\n', dest);
    i = spacept + 1;
  }
}

void chsub(char* string, char c1, char c2) 
{ // Replace each c1 with c2 in string
  int i;
  size_t len = strlen(string);

  for(i = 0; i < len; i++) {
    if(string[i] == c1) {
      string[i] = c2;
    }
  }
}

char* sympathf(char* path)
{ // Make symbol from filename
  char* sym;

  sym = malloc(strlen(basename(path)) + 1);
  if(sym == NULL) {
    fprintf(stderr, "sympathf error: %s", strerror(errno));
    exit(-1);
  }
  strcpy(sym, basename(path));
  chsub(sym, '.', '_');
  chsub(sym, '-', '_');
  chsub(sym, '~', '_');
  chsub(sym, ' ', '_');
  // TODO: make it to be able to substitute all the characters above in
  // one funcall.

  return sym;
}

off_t fsize(const char* path)
{ // Get file size
  struct stat st;

  if(stat(path, &st) == 0) {
    return st.st_size;
  }
  fprintf(stderr, "Unable to determine size of \"%s\": %s (errno %i)\n",
      path, strerror(errno), errno);
  return -1;
}

int main(int argc, char** argv)
{ // Program entry point commented obviously
  int i;
  FILE* target;
  int pathc = argc - 2;
  char** pathv = argv + 2;
  char* sym;

  if(argc < 3) {
    printf("Usage: %s [target] [file] <files...>\n", argv[0]);
    return -1;
  }
  errno = 0;
  if(strcmp(argv[1], "stdout") == 0) {
    target = stdout;
  } else {
    target = fopen(argv[1], "w");
  }
  fprintf(target, "# This file was generated by DOTOIFY utility\n"
                  "# to be compiled with GNU Assembler like this:\n"
                  "#   gcc -c %s\n\n", argv[1]);
  fprintf(target, ".data\n");
  for(i = 0; i < pathc; i++) {
    sym = sympathf(pathv[i]);
    fprintf(target, "# file %s\n", pathv[i]);
    fprintf(target, ".global %s\n", sym);
    fprintf(target, ".global %s_size\n", sym);
    //fprintf(target, ".align 4\n"); // why did I thought i need theese?
    fprintf(target, "%s: .incbin \"%s\"\n", sym, pathv[i]);
    //fprintf(target, ".align 4\n");
    fprintf(target, "%s_size: .quad %lli\n\n",
        sym, (long long int)fsize(pathv[i]));
    free(sym);
  }
  if(target != stdout) {
    fclose(target);
  }
  return 0;
}
